# Generated by Django 4.1.3 on 2022-12-10 02:13

import backend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(default=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=backend_app.models.gen_code, max_length=8, unique=True),
        ),
    ]
